dist: focal
arch: ppc64le
group: dev
script:
  - echo "ganesh"
  - rm -rf hello_world
  - ls
  - /opt/at14.0/bin/gcc hello_world.c -o hello_world
  - ls
  - ./hello_world > ganesh.text
  - cat ganesh.txt
