# dist: focal
# arch: ppc64le
# group: dev
# script:
#   - rm -rf hello_world
#   - /opt/at14.0/bin/gcc hello_world.c -o hello_world
#   - ./hello_world
language: c
  
jobs:
  include:
  - dist: xenial
    arch: ppc64le
    group: dev
    script:
      - rm -rf hello_world
      - /opt/at14.0/bin/gcc hello_world.c -o hello_world
      - ./hello_world
  - dist: bionic
    arch: ppc64le
    group: dev
    script:
      - rm -rf hello_world
      - /opt/at14.0/bin/gcc hello_world.c -o hello_world
      - ./hello_world
  - dist: focal
    arch: ppc64le
    group: dev
    script:
      - rm -rf hello_world
      - /opt/at14.0/bin/gcc hello_world.c -o hello_world
      - ./hello_world
  - dist: xenial
    arch: amd64
    group: dev
    script:
      - rm -rf hello_world
      - /opt/at14.0/bin/gcc hello_world.c -o hello_world
      - ./hello_world
  - dist: bionic
    arch: amd64
    group: dev
    script:
      - rm -rf hello_world
      - /opt/at14.0/bin/gcc hello_world.c -o hello_world
      - ./hello_world
  - dist: focal
    arch: amd64
    group: dev
    script:
      - rm -rf hello_world
      - /opt/at14.0/bin/gcc hello_world.c -o hello_world
      - ./hello_world
