language: c
  
jobs:
  include:
  - dist: xenial
    arch: ppc64le
    #group: edge
    group: dev
    script:
      - /opt/at12.0/bin/gcc hello_world.c -o hello_world
      - ./hello_world
  - dist: bionic
    arch: ppc64le
    #group: edge
    group: dev
    script:
      #- clang -coverage -O0 hello_world.c -o hello_world
      - /opt/at14.0/bin/gcc hello_world.c -o hello_world
      - ./hello_world
  - dist: focal
    arch: ppc64le
    #group: edge
    group: dev
    script:
      #- clang -coverage -O0 hello_world.c -o hello_world
      - /opt/at14.0/bin/gcc hello_world.c -o hello_world
      - ./hello_world
